name: Update README with recent activity

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:     # Allows manual trigger

jobs:
  update-readme:
    name: Update README with recent activity
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: './.github/recent-activity.config.yml'
          GH_USERNAME: Albonire
