name: Update README with recent activity

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:     # Allows manual trigger

jobs:
  update-readme:
    name: Update README with recent activity
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_LINES: 5
          USERNAME: Albonire
