name: Update README with Recent Activity
on:
  schedule:
    # Se ejecuta cada hora
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Update README
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://github.com/Albonire.atom"
          max_post_count: 5
          readme_path: "./README.md"
          template: "
- [$title]($url) - *$date*"
          date_format: "dd/mm/yyyy"
